### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by steffen9000** [dhn/enpass2pass#1]
Please make sure to license your derivative work under the GPL. 

Original source: https://github.com/steffen9000/enpass-decryptor

**Comment by dhn** [comment]
Sorry I've forgotten to add the license. Fixed with https://github.com/dhn/enpass2pass/commit/0f58e1d484121d05a684c1406445a77f853cf25e and https://github.com/dhn/enpass2pass/commit/9ea8e08731bdd3ac19b91a186555371fe75e91e0
